---
- include_tasks: mongodb_pre.yml
- include_tasks: mongodb_install.yml

- block: # Config MongoDB
  - include_tasks: mongodb_search_config.yml
  - include_tasks: mongodb_post.yml
  tags:
    - mongodb-config
